[phases]
static = { commands = ["mkdir -p /output"] }
static = { commands = ["cp -r public/* /output"] }
worker = { commands = ["cp -r worker/* /output"] }

[static]
runtime = "static"

[worker]
runtime = "nodejs"
install = ["npm install"]
build = ["npm run build"]
start = ["wrangler dev"]
